base_frame: "world"
tool_frame: "end_effector"
test_links:
- end_effector

minimum_distance: 0.2
reaction_time: 0.15 

#Information to publish obstacles
publish_obstacles: false
sphere_radius: 0.2
sphere_rgba: [1.0,1.0,1.0,0.2]
